# 2.1.2 Elementwise Vector Operations

As the name suggests, elementwise operations are the operations that are performed across two elements of two different vectors(or a vector and scalar) according to the positions of the elements of those vector(s) or scalar. Note that to perform elementwise operations, both the vectors must be of the same length(except vector scaling where the scalar is a single variable).

Let us dive into some basic elementwise operations that can be performed on vectors. These include addition, subtraction, multiplication and scaling. 
\
\

## 2.1.2.1 Vector Addition

**Definition 2.1.2.1** (Vector Addition). \ Vector Addition is the element-wise sum of two vectors $\mathbf{u}, \mathbf{v} \in \mathbb{R}^n$ to yield another vector $\mathbf{w} \in \mathbb{R}^n$.
$$
\mathbf{u} + \mathbf{v} = \begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix} + \begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n \end{bmatrix} = \begin{bmatrix} u_1 + v_1\\ u_2 + v_2\\ \vdots\\ u_n + v_n \end{bmatrix} \in \mathbb{R}^n
$$
\
Recall that $\mathbb{R}^n$ represents the $n$-dimensional set of real numbers and all vectors are represented in lowercase bold letters.
It can also be represented by $\oplus$.

\
\

**Example 2.1.2.1**
$$
\begin{bmatrix} 5\\ 3\\ \end{bmatrix} + \begin{bmatrix} 2\\ 6\\ \end{bmatrix} = \begin{bmatrix} 5 + 2\\ 3 + 6\\ \end{bmatrix} = \begin{bmatrix} 7\\ 9\\ \end{bmatrix} \in \mathbb{R}^2
$$

\
\
\

## 2.1.2.2 Vector Scaling

**Definition 2.1.2.2** (Vector Scaling). \ Vector scaling is multipying each element $v_i$ of the vector $\mathbf{v} \in \mathbb{R}^n$ with a scalar  $\alpha \in \mathbb{R}$ to yeild another vector $\mathbf{w}$.
$$
\alpha \mathbf{v} = \alpha \begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n \end{bmatrix} = \begin{bmatrix} \alpha v_1\\ \alpha v_2\\ \vdots\\ \alpha v_n \end{bmatrix} \in \mathbb{R}^n
$$

Sometimes, we also use $\dot$ to represent vector scaling.
\
\

**Example 2.1.2.2**
$$
5 \begin{bmatrix} 4\\ 6\\ \end{bmatrix} = \begin{bmatrix} 5*4\\ 5*6\\ \end{bmatrix} = \begin{bmatrix} 20\\ 30\\ \end{bmatrix} \in \mathbb{R}^2
$$


## 2.1.2.3 Vector Subtraction

**Definition 2.1.2.3** (Vector Subtraction). \ Vector subtraction is the elementwise addition of a vector $\mathbf{u} \in \mathbb{R}^n$ with the vector $\mathbf{v} \in \mathbb{R}^n$ scaled by a factor of -1.
$$
\mathbf{u} - \mathbf{v} = \begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix} + -1 \begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n \end{bmatrix} = 
\begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix} + \begin{bmatrix} -v_1\\ -v_2\\ \vdots\\ -v_n \end{bmatrix} = \begin{bmatrix} u_1 + (-v_1)\\ u_2 + (-v_2)\\ \vdots\\ u_n + (-v_n) \end{bmatrix} = \begin{bmatrix} u_1 - v_1\\ u_2 - v_2\\ \vdots\\ u_n - v_n \end{bmatrix} \in \mathbb{R}^n
$$
\

**Example 2.1.2.3**
$$
\begin{bmatrix} 7\\ 3\\ \end{bmatrix} - \begin{bmatrix} 1\\ 8\\ \end{bmatrix} = \begin{bmatrix} 7\\ 3 \end{bmatrix} + -1 \begin{bmatrix} 1\\ 8\\ \end{bmatrix} = 
\begin{bmatrix} 7\\ 3 \end{bmatrix} + \begin{bmatrix} -1\\ -8 \end{bmatrix} = \begin{bmatrix} 7 + (-1)\\ 3 + (-8) \end{bmatrix} = \begin{bmatrix} 7 - 1\\ 3 - 8 \end{bmatrix} = \begin{bmatrix} 6\\ -5 \end{bmatrix} \in \mathbb{R}^2
$$

\
\

## 2.1.2.4 Scaled Vector Addition

**Definition 2.1.2.4** (Scaled Vector Addition). \ Scaled Vector Addition is the elementwise addition of a vector $\mathbf{u} \in \mathbb{R}^n$ with the vector $\mathbf{v} \in \mathbb{R}^n$ scaled by a factor of $\alpha$.
$$
\mathbf{u} + \alpha \mathbf{v} = \begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix} + \alpha \begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n \end{bmatrix} = 
\begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix} + \begin{bmatrix} \alpha v_1\\  \alpha v_2\\ \vdots\\ \alpha v_n \end{bmatrix} = \begin{bmatrix} u_1 + \alpha v_1\\ u_2 + \alpha v_2\\ \vdots\\ u_n + \alpha v_n \end{bmatrix} \in \mathbb{R}^n
$$

It is same as vector subtraction when $\alpha$ = -1.
\
\
**Example 2.1.2.4**
$$
\begin{bmatrix} 6\\ 8\\ \end{bmatrix} + 4 \begin{bmatrix} 3\\ 5\\ \end{bmatrix} = \begin{bmatrix} 6\\ 8 \end{bmatrix} + \begin{bmatrix} 4*3\\ 4*5 \end{bmatrix} = \begin{bmatrix} 6 + 12\\ 8 + 20 \end{bmatrix} = \begin{bmatrix} 18\\ 28 \end{bmatrix} \in \mathbb{R}^2
$$
\
\

## 2.1.2.5 Hadamard Product

**Definition 2.1.2.5** (Hadamard Product). \ The Hadamard product, also known as the elementwise product, is the component-wise multiplication of two vectors $\mathbf{u}, \mathbf{v} \in \mathbb{R}^n$ to yield another vector $\mathbf{w} \in \mathbb{R}^n$:
$$
\mathbf{u} \circ \mathbf{v} = \begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix} \circ \begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n \end{bmatrix} = \begin{bmatrix} u_1 v_1\\ u_2 v_2\\ \vdots\\ u_n v_n \end{bmatrix} \in \mathbb{R}^n
$$

Note that the Hadamard product is different from the dot product, which results in a scalar, while hadamard product results in a vector. There are some other symbols also such as $\odot$ and $*$ which are used to denote hadamard product.

\
\

**Example 2.1.2.5**
$$
\begin{bmatrix} 2\\ 4 \end{bmatrix} \circ \begin{bmatrix} 5\\ 3 \end{bmatrix} = \begin{bmatrix} 2 \cdot 5\\ 4 \cdot 3 \end{bmatrix} = \begin{bmatrix} 10\\ 12 \end{bmatrix} \in \mathbb{R}^2
$$

\
\
\

## 2.1.2.6 Broadcasting (in Python)

**Definition 2.1.2.6 (Broadcasting).**  Broadcasting is a concept which allows us to automatically adjust or reshape the arrays of different shapes during arithmetic operations.

It allows concise, efficient computation without replicating data. This is especially useful in deep learning and computer vision when we apply operations like scaling or offsetting across entire datasets, images, or tensors. For example, applying the same transformation (like brightness increase) to all image pixels or add a bias vector to every row in a data matrix.

#### Example 2.1.2.6.1 (NumPy):
Broadcasting a scalar to a 1d array:
```{python}
import numpy as np

# Vector u has shape (3,)
u = np.array([1, 2, 3])

# Scalar multiplication
print(5 * u)
```

#### Example 2.1.2.6.2 (NumPy):
Broadcasting a 1d array to a 2d array:
```{python}
# Add bias to a matrix row-wise
A = np.array([[1, 2, 3],
              [4, 5, 6]])
bias = np.array([10, 20, 30])
print(A + bias)
```

\
\

### Vectorization and Broadcasting

Vectorization refers to performing paralellized operations on entire arrays (or vectors) without using explicit loops which perform operations one by one. This greatly speeds up the computation and makes it faster.

Broadcasting enables vectorization by allowing arrays with smaller shapes to be expanded implicitly during arithmetic operations, eliminating the need for nested loops.

#### Example 2.1.2.6.3 (NumPy):
Loop vs Vectorized Operations

```{python}
import numpy as np
import time

# Generate large data
A = np.random.rand(10000, 100)
bias = np.random.rand(100)

# Manual loop (non-vectorized)
start = time.time()
A_loop = np.zeros_like(A)
for i in range(A.shape[0]):
    A_loop[i] = A[i] + bias
end = time.time()
loop_time = end-start
print("Loop time:", end - start, "seconds")

# Vectorized using broadcasting
start = time.time()
A_broadcast = A + bias
end = time.time()
broadcast_time = end-start
print("Broadcast (vectorized) time:", end - start, "seconds")
print(str((loop_time/broadcast_time))+"x Improvement")
```