# 2.1.1 Basic Introduction to Vectors

Vectors have relatively different meanings in physics, math and CS. In physics, vectors can be thought of as an arrow having both magnitude and direction. In CS, vectors can be thought of as an array/ordered list of numbers. While in math, we present a more generalized definition of vectors.

**Definition 2.1.1.1** (Vector). \ A vector is an ordered one-dimensional array which can be added together or multiplied by a scalar.

Mathematically, a vector $v$ $\in$ $\mathbb{R}^n$ is written as:
\begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{bmatrix}
where $v_1, v_2, \ldots, v_n$ are the components of the $n$-dimensional vector $v$. 

---

## Vectors as coordinate systems

In Linear Algebra, vectors are often used in coordinate systems. Let's think about vectors as arrows in $2D$ graphs. The tail of the arrow is at the origin, where the $x$-axis and $y$-axis meet. From there, there is a line till the tip of the arrow, which is located where the elements of the 2-dimensional vector point to a coordinate of the graph. Note that vectors are not points, but are arrows from the origin to the point.

Similarly, for 3D graphs, the tail of the arrow is at the origin. From there, there is a line till the tip of the arrow, which is located where the elements of the 3-dimensional vector point to a coordinate of the graph. We can also generalize this to n-dimensional spaces for n-dimensional vectors.