# Linear Combinations and Basis Vectors
## Linear Combinations
**Definition 2.3.1.1** (Linear Combinations). Given $k$ vectors, $\mathbf{u_1}, \mathbf{u_2}, \dots, \mathbf{u_{k}} \in \mathbb{R}^n$ and $k$ scalars $\alpha_1, \alpha_2, \dots, \alpha_{k} \in \mathbb{R}$, a **linear combination** of the $k$ vectors using the scalars is

$$
\sum_{i=1}^{k} \alpha_i \mathbf{u_i} = 
\alpha_1 \mathbf{u_1} + \alpha_2 \mathbf{u_2} + \dots + \alpha_{k} \mathbf{u_{k}}
$$

$$
= \alpha_1 \begin{bmatrix} u_1(1)\\ u_1(2)\\ \vdots\\ u_1(n) \end{bmatrix} + \alpha_2 \begin{bmatrix} u_2(1)\\ u_2(2)\\ \vdots\\ u_2(n) \end{bmatrix} + \dots + \alpha_k \begin{bmatrix} u_k(1)\\ u_k(2)\\ \vdots\\ u_k(n) \end{bmatrix}
$$
$$
= \begin{bmatrix} \alpha_1 u_1(1) + \alpha_2 u_2(1) + \dots + \alpha_k u_k(1) \\ \alpha_1 u_1(2) + \alpha_2 u_2(2) + \dots + \alpha_k u_k(2) \\ \vdots \\ \alpha_1 u_1(n) + \alpha_2 u_2(n) + \dots + \alpha_k u_k(n) \end{bmatrix} \in \mathbb{R}^n
$$
$$
\mathbf{L} : \underbrace{\mathbb{R} \times \mathbb{R}^n \times \dots \times \mathbb{R} \times \mathbb{R}^n}_{k\text{ times}} \rightarrow \mathbb{R}^n
$$
\

\
**Example 2.3.1.1**
Given two vectors $\mathbf{u}=\begin{bmatrix} 2\\ 8\\ \end{bmatrix}, \mathbf{v}=\begin{bmatrix} 7\\ 9\\ \end{bmatrix}$ and two scalars $\alpha$=2, $\beta$=3, find their liner combination.
$$
\alpha \mathbf{u} + \beta \mathbf{v} =
2\begin{bmatrix} 2\\ 8\\ \end{bmatrix} + 3 \begin{bmatrix} 7\\ 9\\ \end{bmatrix} = \begin{bmatrix} 2*2\\ 2*8 \end{bmatrix} + \begin{bmatrix} 3*7\\ 3*9 \end{bmatrix} = \begin{bmatrix} 4 + 21\\ 16 + 27 \end{bmatrix} = \begin{bmatrix} 25\\ 43 \end{bmatrix} \in \mathbb{R}^2
$$

## Standard Basis Vectors

There exists a set of vectors where all the $n$ indices are 0, except the $i^{th}$ index which is 1.
$$
\mathbf{e_j} = \begin{bmatrix} 0\\ \vdots\\ 1\\ \vdots\\ 0 \end{bmatrix} \leftarrow e_{ji}
$$
Hence, we get a set of vectors {$\mathbf{e_1}, \mathbf{e_2} \dots \mathbf{e_n}$} $\subset \mathbb{R}^n$.


If you notice carefully, these set of vectors are the columns of the $n$-dimensional Identity Matrix $\mathbb{I}^n$. Each column $i_j$  in  $\mathbb{I}^n$ is the $j^{th}$ standard basis vector

For example, in a 3 dimensional Identity Matrix, 
$$
\mathbb{I}^3 = 
\begin{bmatrix} 1&0&0\\ 0&1&0\\ 0&0&1 \end{bmatrix}
$$
The first column $i_1$ is the basis vector with $j$ = 1, the second column $i_2$ is the basis vector with $j$ = 2 and the third column $i_3$ is the basis vector with $j$ = 3

$$\begin{bmatrix} 1\\ 0\\ 0 \end{bmatrix},
\begin{bmatrix} 0\\ 1\\ 0 \end{bmatrix},
\begin{bmatrix} 0\\ 0\\ 1 \end{bmatrix}$$

Antoher interesting fact about these standard basis vectors is that the linear combination of $n$-dimensional standard basis vectors with n scalars can point to any direction in an $n$-dimensional space. Let us start by presenting an example in a $2$-dimensional space. The $2$-dimensional standard basis vectors are:
$$
\begin{bmatrix} 1\\ 0 \end{bmatrix},
\begin{bmatrix} 0\\ 1 \end{bmatrix}
$$

Now let us think of vectors as arrows in a graph. Take two scalars $\alpha$ = 3, $\beta$ = 2. The linear combination of the standard basis vectors with these scalars, gives a vector(arrow) pointing towards the coordinates on a graph.
$$
3\begin{bmatrix} 1\\ 0\\ \end{bmatrix} + 2 \begin{bmatrix} 0\\ 1\\ \end{bmatrix} = \begin{bmatrix} 3*1\\ 3*0 \end{bmatrix} + \begin{bmatrix} 2*0\\ 2*1 \end{bmatrix} = \begin{bmatrix} 3 + 0\\ 0 + 2 \end{bmatrix} = \begin{bmatrix} 3\\ 2 \end{bmatrix}
$$