# Random Variables

More than occasionally, measuring the probability of events (i.e., subsets of outcomes in our state space $S$) becomes unwieldy. Often times the quantities we want to represent cannot be easily expressed in terms of subsets of the state space $S$, which may be incredibly complex, high-dimensional, or non-numeric. For example, suppose we want to survey 10,000 people and determine if their opinion about hamburgers is positive or negative. The sample space (the space of all outcomes) here has $2^{10,000}$ outcomes (a truly staggering number), and each outcome $x \in S$ can be represented by a $10,000$-bit string (where the $i$th position is the opinion of the $i$th person, $1 \leq i \leq 10,000$). This sample space is so vast (and of course, the probability of all outcomes would not be the same as it would be for tossing fair coins).

Let us assume now we want to ask a simple question: "What is the probability that at least 3,000 of 10,000 (30%) of the population like hamburgers?" Assuming there is some function $p: S \rightarrow [0,1]$ which assigns a probability value to each of the $|S| = 2^{10,000}$ outcomes, we can represent this as the probability of an event $A$, where $A$ is the subset of outcomes where at least 3,000 people had a positive opinion.

Let’s assume we want to ask a slightly more complex question: "What is the yearly salary of Indian women under the age of 30 who like hamburgers?" Suddenly, this becomes impossible to express using events. Assuming we captured details like salary, ethnicity, age, and gender for each of the 10,000 respondents
