# Why study measure-theoretic probability?

This section introduces measure theory with a focus on probability and only from the perspective of learning measure theoretic probability. This is useful for later concepts on stochastic processes for which measure theoretic probability becomes essential. Other texts tackle measure theory in full, but we do not need it. We only need to a few the core results which are necessary to gain a deeper understanding of probability. 

Recall that the modern definition of probability originated from Kolgormov's axioms of probability, which he introduced in 1933 in his book "". However, the axioms that we studied were not all that he introduced. Particularly, Kolgormov's work in 1933 set the foundation for probability in measure-theoretic concepts, which was a formalism that has stayed on till today. The modern theory of probability is rigorously based on measure theory. And as we shall soon see, a lot of the results in probability theory which we have derived, are based in measure-theoretic fundamentals. 

An important question arises: is measure theory necessary for a deep understanding of probability? This is a hotly debated topic. Jaynes (2003), for example, argues that it might not be necessary (emphasis ours):

> Appendex B.3 Willy Feller on measure theory. 
> In contrast to our policy, many expositions of probability theory begin at the outset to try to assign probabilities on infinite sets, both countable or uncountable. Those who use measure theory are, in effect, supposing the passage to an infinite set already accomplished before introducing probabilities. For example, Feller advocates this policy and uses it throughout his second volume (Feller, 1966).
> In discussing this issue, Feller (1966) notes that specialists in various applications sometimes ‘deny the need for measure theory because they are unacquainted with problems of other types and with situations where vague reasoning did lead to wrong results’. **If Feller knew of any case where such a thing has happened, this would surely have been the place to cite it – yet he does not. Therefore we remain, just as he says, unacquainted with instances where wrong results could be attributed to failure to use measure theory.**
> But, as noted particularly in Chapter 15, there are many documentable cases where careless use of infinite sets has led to absurdities. We know of no case where our ‘cautious approach’ policy leads to inconsistency or error; or fails to yield a result that is reasonable.
> [...]
> But on this issue, too, we are not fanatics. We recognize that the language of set and measure theory was a useful development in terminology, in some cases enabling one to state mathematical propositions with a generality and conciseness that is quite lacking in 19th century mathematics. Therefore we are happy to use that language whenever it contributes to our goal, and we could hardly get along without an occasional ‘almost everywhere’ or ‘of measure zero’ phrase. However, when we use a bit of measure theory, it is never in the thought that this makes the argument more rigorous; but only a recognition of the compactness of that language.
> **Of course, we stand ready and willing to use set and measure theory – just as we stand ready and willing to use number theory, projective geometry, group theory, topology, or any other part of mathematics – wherever this should prove helpful for the technique of finding a result or for understanding it.** But we see no reason why we must state every proposition in set/measure theory terminology and notation in cases where plain English is clearer and, as far as we can see, not only more efficient for our purposes but actually safer. 
> [...] **To give every old, familiar notion a new, impressive name and symbol unknown to Gauss and Cauchy has nothing to do with rigor. It is, more often than not, a form of gamesmanship whose real purpose is to conceal the Mickey Mouse triviality of what is being done. One would blush to state it in plain English.**

We wholeheartedly agree with this stance, which is why we have dedicated several chapters to a thorough treatment of probability theory without any mention of measure theory. However, in this chapter we bow to a practical requirement: many results in advanced probability texts, especially stochastic processes, require some foundation in measure theory just to be able to understand what the author is saying. For that reason, we introduce measure theory, but restricted to the lens of probability. 